"""change column type coins from decimal to integer

Revision ID: 20251201_002
Revises: 20251201_001
Create Date: 2025-12-01 20:02:12.315861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251201_002'
down_revision: Union[str, Sequence[str], None] = '20251201_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_up', 'coins',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_up', 'coins',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###
