"""change column type coins from integer to decimal

Revision ID: 20251201_003
Revises: 20251201_002
Create Date: 2025-12-02 10:42:48.946965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251201_003'
down_revision: Union[str, Sequence[str], None] = '20251201_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_up', 'coins',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_up', 'coins',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
