"""Init table (top_up,wallet,partner_wallet,wallet_history,partner_wallet_history)

Revision ID: 20251201_001
Revises: 
Create Date: 2025-12-01 19:52:42.345944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251201_001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_wallet',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('rec_by', sa.String(length=32), nullable=False),
    sa.Column('rec_date', sa.DateTime(), nullable=False),
    sa.Column('mod_by', sa.String(length=32), nullable=True),
    sa.Column('mod_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('top_up',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('coins', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('rec_by', sa.String(length=32), nullable=False),
    sa.Column('rec_date', sa.DateTime(), nullable=False),
    sa.Column('mod_by', sa.String(length=32), nullable=True),
    sa.Column('mod_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('rcoins', sa.Integer(), nullable=False),
    sa.Column('rec_by', sa.String(length=32), nullable=False),
    sa.Column('rec_date', sa.DateTime(), nullable=False),
    sa.Column('mod_by', sa.String(length=32), nullable=True),
    sa.Column('mod_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_wallet_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('wallet_id', sa.String(length=32), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('ctype', sa.String(length=10), nullable=False, comment='TOPUP, USE'),
    sa.Column('ref_id', sa.String(length=32), nullable=False, comment='ctype=USE, partner distribute coins to member'),
    sa.Column('rec_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_wallet_history_wallet_id'), 'partner_wallet_history', ['wallet_id'], unique=False)
    op.create_table('wallet_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('wallet_id', sa.String(length=32), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('ctype', sa.String(length=10), nullable=False, comment='TOP_UP, TRF_IN, TRF_OUT, REWARD, USE'),
    sa.Column('ref_id', sa.String(length=32), nullable=False, comment='TRF_IN -> receive coins from member, TRF_OUT -> transfer to member, REWARD -> get reward, USE -> spend on'),
    sa.Column('sub_ref', sa.String(length=32), nullable=False, comment='can be movie_id, episode_id, etc'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rec_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_history_wallet_id'), 'wallet_history', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_history_wallet_id'), table_name='wallet_history')
    op.drop_table('wallet_history')
    op.drop_index(op.f('ix_partner_wallet_history_wallet_id'), table_name='partner_wallet_history')
    op.drop_table('partner_wallet_history')
    op.drop_table('wallet')
    op.drop_table('top_up')
    op.drop_table('partner_wallet')
    # ### end Alembic commands ###
