"""
new collection

Autogenerated migration:
- New collection: brand
"""

revision = '20251230120456'
down_revision = '20251223162840'
branch_labels = None
depends_on = None


def upgrade(env):
    """Apply schema changes"""
    env.create_collection('brand')
    env.db['brand'].create_index((('rec_date', 1),))
    env.db['brand'].create_index((('org_id', 1),))
    env.db['brand'].create_index((('uid', 1),))
    env.db['_feature'].insert_many([
        {'_id': 'brand', 'feature_name': 'brand', 'negasiperm': {'1': 240, '2': 240, '4': 255, '8': 255}, 'authority': 3}
    ])


def downgrade(env):
    """Revert schema changes"""
    env.drop_collection('brand')
    env.db['_feature'].delete_one({'_id': 'brand'})
