"""
initial schema

Autogenerated migration:
- New collections: _dmsfile, giveaway, content_video, _audittrail, content, _feature, _role, ads, _organization, _user, _enum, _dmsindexlist, _featureonrole, bundling, qr_product, _dmsfolder, _dmsdoctype
"""

revision = '20251210224217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(env):
    """Apply schema changes"""
    # Create collection: _dmsfile
    env.create_collection('_dmsfile')
    env.db['_dmsfile'].create_index([('rec_date', 1)])
    env.db['_dmsfile'].create_index([('doctype', 1)])
    env.db['_dmsfile'].create_index([('folder_id', 1)])
    env.db['_dmsfile'].create_index([('refkey_id', 1)])
    env.db['_dmsfile'].create_index([('org_id', 1)])
    env.db['_dmsfile'].create_index([('refkey_id', 1), ('refkey_table', 1)], name='refkey_id_table')

    # Create collection: giveaway
    env.create_collection('giveaway')
    env.db['giveaway'].create_index([('rec_date', 1)])
    env.db['giveaway'].create_index([('uid', 1)])
    env.db['giveaway'].create_index([('org_id', 1)])

    # Create collection: content_video
    env.create_collection('content_video')
    env.db['content_video'].create_index([('rec_date', 1)])
    env.db['content_video'].create_index([('content_id', 1)])
    env.db['content_video'].create_index([('org_id', 1)])

    # Create collection: _audittrail
    env.create_collection('_audittrail')
    env.db['_audittrail'].create_index([('rec_date', 1), ('org_id', 1), ('uid', 1)])

    # Create collection: content
    env.create_collection('content')
    env.db['content'].create_index([('rec_date', 1)])
    env.db['content'].create_index([('org_id', 1)])

    # Create collection: _feature
    env.create_collection('_feature')
    env.db['_feature'].create_index([('feature_name', 1)])
    # Initial data for _feature
    env.db['_feature'].insert_many([
        {'_id': '_user', 'feature_name': '_user', 'negasiperm': {'1': 248, '2': 248, '4': 248, '8': 248}, 'authority': 15},
        {'_id': '_role', 'feature_name': '_role', 'negasiperm': {'1': 248, '2': 248, '4': 255, '8': 255}, 'authority': 3},
        {'_id': '_enum', 'feature_name': '_enum', 'negasiperm': {'1': 240, '2': 255, '4': 255, '8': 255}, 'authority': 1},
        {'_id': '_audittrail', 'feature_name': '_audittrail', 'negasiperm': {'1': 254, '2': 254, '4': 254, '8': 254}, 'authority': 15},
        {'_id': '_feature', 'feature_name': '_feature', 'negasiperm': {'1': 250, '2': 250, '4': 255, '8': 255}, 'authority': 3},
        {'_id': '_menu', 'feature_name': '_menu', 'negasiperm': {'1': 250, '2': 255, '4': 255, '8': 255}, 'authority': 1},
        {'_id': '_organization', 'feature_name': '_organization', 'negasiperm': {'1': 248, '2': 250, '4': 250, '8': 250}, 'authority': 15},
        {'_id': '_dashboard', 'feature_name': '_dashboard', 'negasiperm': {'1': 254, '2': 254, '4': 254, '8': 254}, 'authority': 15},
        {'_id': '_myorg', 'feature_name': '_myorg', 'negasiperm': {'1': 250, '2': 250, '4': 250, '8': 250}, 'authority': 15},
        {'_id': '_myprofile', 'feature_name': '_myprofile', 'negasiperm': {'1': 250, '2': 250, '4': 250, '8': 250}, 'authority': 15},
        {'_id': '_dmsindexlist', 'feature_name': '_dmsindexlist', 'negasiperm': {'1': 248, '2': 255, '4': 255, '8': 255}, 'authority': 1},
        {'_id': '_dmsdoctype', 'feature_name': '_dmsdoctype', 'negasiperm': {'1': 248, '2': 255, '4': 255, '8': 255}, 'authority': 1},
        {'_id': '_dmsbrowse', 'feature_name': '_dmsbrowse', 'negasiperm': {'1': 96, '2': 255, '4': 255, '8': 255}, 'authority': 1},
        {'_id': 'content', 'feature_name': 'content', 'negasiperm': {'1': 64, '2': 254, '4': 254, '8': 254}, 'authority': 15},
        {'_id': 'register', 'feature_name': 'register', 'negasiperm': {'1': 255, '2': 255, '4': 252, '8': 255}, 'authority': 4},
        {'_id': 'wallet', 'feature_name': 'wallet', 'negasiperm': {'1': 248, '2': 252, '4': 252, '8': 252}, 'authority': 15},
        {'_id': 'topup', 'feature_name': 'topup', 'negasiperm': {'1': 248, '2': 252, '4': 252, '8': 252}, 'authority': 15},
        {'_id': 'ads', 'feature_name': 'ads', 'negasiperm': {'1': 254, '2': 240, '4': 255, '8': 255}, 'authority': 3},
        {'_id': 'qr_product', 'feature_name': 'qr_product', 'negasiperm': {'1': 254, '2': 240, '4': 255, '8': 255}, 'authority': 3},
        {'_id': 'bundling', 'feature_name': 'bundling', 'negasiperm': {'1': 254, '2': 240, '4': 255, '8': 255}, 'authority': 3},
        {'_id': 'giveaway', 'feature_name': 'giveaway', 'negasiperm': {'1': 254, '2': 240, '4': 255, '8': 252}, 'authority': 11},
    ])

    # Create collection: _role
    env.create_collection('_role')
    env.db['_role'].create_index([('rec_date', 1)])
    env.db['_role'].create_index([('name', 1), ('org_id', 1)])

    # Create collection: ads
    env.create_collection('ads')
    env.db['ads'].create_index([('rec_date', 1)])
    env.db['ads'].create_index([('uid', 1)])
    env.db['ads'].create_index([('org_id', 1)])

    # Create collection: _organization
    env.create_collection('_organization')
    env.db['_organization'].create_index([('rec_date', 1), ('authority', 1), ('ref_id', 1), ('plan_id', 1)])

    # Create collection: _user
    env.create_collection('_user')
    env.db['_user'].create_index([('rec_date', 1)])
    env.db['_user'].create_index([('username', 1)])
    env.db['_user'].create_index([('email', 1)])
    env.db['_user'].create_index([('org_id', 1)])
    env.db['_user'].create_index([('r_id', 1)])
    env.db['_user'].create_index([('id', 1), ('org_id', 1)], name='id_orgid')
    env.db['_user'].create_index([('username', 1), ('org_id', 1)], name='username_orgid')
    env.db['_user'].create_index([('email', 1), ('org_id', 1)], name='email_orgid')

    # Create collection: _enum
    env.create_collection('_enum')
    env.db['_enum'].create_index([('app', 1)])
    env.db['_enum'].create_index([('mod', 1)])
    env.db['_enum'].create_index([('code', 1)])
    env.db['_enum'].create_index([('rec_date', 1)])
    env.db['_enum'].create_index([('org_id', 1)])
    env.db['_enum'].create_index([('type', 1)])
    env.db['_enum'].create_index([('app', 1), ('mod', 1)], name='app_mod')
    env.db['_enum'].create_index([('app', 1), ('mod', 1), ('org_id', 1)], name='app_mod_org')
    env.db['_enum'].create_index([('org_id', 1), ('type', 1)], name='org_type')
    env.db['_enum'].create_index([('app', 1), ('mod', 1), ('_sort', 1)], name='app_mod_sort')
    # Initial data for _enum
    env.db['_enum'].insert_many([
        {'_id': 'AUTHORITY', 'app': 'baseapp', 'mod': 'AUTHORITY', 'code': 'AUTHORITY', 'type': 'hardcoded', 'value': {'owner': 1, 'partner': 2, 'client': 4, 'affiliator': 8}},
        {'_id': 'ROLEACTION', 'app': 'baseapp', 'mod': 'ROLEACTION', 'code': 'ROLEACTION', 'type': 'hardcoded', 'value': {'view': 1, 'add': 2, 'edit': 4, 'delete': 8, 'export': 16, 'import': 32, 'approval': 64, 'setting': 128}},
        {'_id': 'dmsDataType', 'app': 'baseapp', 'mod': 'dmsDataType', 'code': 'dmsDataType', 'type': 'hardcoded', 'value': ['String', 'Integer', 'Datetime']},
        {'_id': 'SEX', 'app': 'baseapp', 'mod': 'SEX', 'code': 'SEX', 'type': 'hardcoded', 'value': ['Male', 'Female']},
        {'_id': 'GENRE', 'app': 'baseapp', 'mod': '_enum', 'code': 'genre', 'type': 'hardcoded', 'value': 'Genre'},
    ])

    # Create collection: _dmsindexlist
    env.create_collection('_dmsindexlist')
    env.db['_dmsindexlist'].create_index([('rec_date', 1)])
    env.db['_dmsindexlist'].create_index([('name', 1)])
    env.db['_dmsindexlist'].create_index([('org_id', 1)])
    env.db['_dmsindexlist'].create_index([('name', 1), ('org_id', 1)], name='index_orgid')

    # Create collection: _featureonrole
    env.create_collection('_featureonrole')
    env.db['_featureonrole'].create_index([('f_id', 1)])
    env.db['_featureonrole'].create_index([('r_id', 1)])
    env.db['_featureonrole'].create_index([('org_id', 1)])
    env.db['_featureonrole'].create_index([('r_id', 1), ('f_id', 1)], name='rf_id')

    # Create collection: bundling
    env.create_collection('bundling')
    env.db['bundling'].create_index([('rec_date', 1)])
    env.db['bundling'].create_index([('uid', 1)])
    env.db['bundling'].create_index([('org_id', 1)])

    # Create collection: qr_product
    env.create_collection('qr_product')
    env.db['qr_product'].create_index([('rec_date', 1)])
    env.db['qr_product'].create_index([('uid', 1)])
    env.db['qr_product'].create_index([('org_id', 1)])

    # Create collection: _dmsfolder
    env.create_collection('_dmsfolder')
    env.db['_dmsfolder'].create_index([('rec_date', 1)])
    env.db['_dmsfolder'].create_index([('folder_name', 1)])
    env.db['_dmsfolder'].create_index([('level', 1)])
    env.db['_dmsfolder'].create_index([('pid', 1)])
    env.db['_dmsfolder'].create_index([('org_id', 1)])
    env.db['_dmsfolder'].create_index([('level', 1), ('org_id', 1)], name='_lo')
    env.db['_dmsfolder'].create_index([('folder_name', 1), ('level', 1), ('org_id', 1)], name='_flo')
    env.db['_dmsfolder'].create_index([('folder_name', 1), ('level', 1), ('org_id', 1), ('pid', 1)], name='_flop')

    # Create collection: _dmsdoctype
    env.create_collection('_dmsdoctype')
    env.db['_dmsdoctype'].create_index([('rec_date', 1)])
    env.db['_dmsdoctype'].create_index([('org_id', 1)])
    env.db['_dmsdoctype'].create_index([('name', 1), ('org_id', 1)], name='name_orgid')



def downgrade(env):
    """Revert schema changes"""
    env.drop_collection('_dmsfile')
    env.drop_collection('giveaway')
    env.drop_collection('content_video')
    env.drop_collection('_audittrail')
    env.drop_collection('content')
    env.drop_collection('_feature')
    env.drop_collection('_role')
    env.drop_collection('ads')
    env.drop_collection('_organization')
    env.drop_collection('_user')
    env.drop_collection('_enum')
    env.drop_collection('_dmsindexlist')
    env.drop_collection('_featureonrole')
    env.drop_collection('bundling')
    env.drop_collection('qr_product')
    env.drop_collection('_dmsfolder')
    env.drop_collection('_dmsdoctype')
