@prod = https://arena.gai.co.id/service
@dev = http://localhost:17178
@host = {{prod}}
@upload_host = {{prod}}

# --- TOKENS ---
# Token Owner (Arena)
@owner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBhcmVuYS5jby5pZCIsImlkIjoiZjc4ODZhOTliNmIyNGVmZmFiYjczYmQ1M2YzYzliMDQiLCJyb2xlcyI6WyI3ZTU3YzBkOTQxYTc0YWE3YTZlZDhhNTI2MGI3MzVkNiJdLCJhdXRob3JpdHkiOjEsIm9yZ19pZCI6IjcxNDgwMTc1NDI5ODQ4NDliYTE3YTlkOGZiMTBiMGZiIiwiZmVhdHVyZXMiOnsiX3VzZXIiOjcsIl9yb2xlIjo3LCJfZW51bSI6MTUsIl9hdWRpdHRyYWlsIjoxLCJfZmVhdHVyZSI6NSwiX21lbnUiOjUsIl9vcmdhbml6YXRpb24iOjcsIl9kYXNoYm9hcmQiOjEsIl9teW9yZyI6NSwiX215cHJvZmlsZSI6NSwiX2Rtc2luZGV4bGlzdCI6MTUsIl9kbXNkb2N0eXBlIjo3LCJfZG1zYnJvd3NlIjoxNTksImNvbnRlbnQiOjE5MSwid2FsbGV0Ijo3LCJ0b3B1cCI6NywiYWRzIjoxLCJxcl9wcm9kdWN0IjoxLCJidW5kbGluZyI6MSwiZ2l2ZWF3YXkiOjF9LCJiaXR3cyI6eyJWSUVXIjoxLCJBREQiOjIsIkVESVQiOjQsIkRFTEVURSI6OCwiRVhQT1JUIjoxNiwiSU1QT1JUIjozMiwiQVBQUk9WQUwiOjY0LCJTRVRUSU5HIjoxMjh9LCJzZXNzaW9uX2lkIjoiMTQ1YmY0MjM4ZDgxNDk5NmE1NjJiYjgxMTIwYTExOTIiLCJleHAiOjE3Njc2MDQzNzksImp0aSI6Ijk1MDUwMDRiMDY0ZjRjODJhMmFjNWQ2OTIxYjQ3MTdmIn0.X_Of2EDbvOy4IafUoi3okcJYNuo7TXgH2k9I75yaMEE
# Token Partner
@partner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBwZWphdGVuLXBoLmNvbSIsImlkIjoiMzY3Mjg1YzUtYWJiYS00NjgzLWJkYzItNTU0ZTQzZWQ1YzM2Iiwicm9sZXMiOlsiY2E3MDQwNGQtYjY1NC00ZGFiLThkMDQtNDFiN2E1YjA0MTQ4IiwiOWQyOTgxNjgtMmMzMi00YjVkLWE5MTUtMmFkNzVhZjdhYWMwIl0sImF1dGhvcml0eSI6Miwib3JnX2lkIjoiNjdiODFmYzAtNTk1NC00YTkzLWJlOGUtNTllZmU2ZWFhNGNlIiwiZmVhdHVyZXMiOnsiX3VzZXIiOjcsIl9yb2xlIjoxNSwiX2VudW0iOjEsIl9hdWRpdHRyYWlsIjoxLCJfZmVhdHVyZSI6NSwiX29yZ2FuaXphdGlvbiI6NywiX2Rhc2hib2FyZCI6MSwiX215b3JnIjo1LCJfbXlwcm9maWxlIjo1LCJfZG1zaW5kZXhsaXN0IjoxLCJfZG1zZG9jdHlwZSI6MSwiX2Rtc2Jyb3dzZSI6MTU5LCJjb250ZW50IjoxODN9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIxMzU5MjF9.12jBjfswWoeFtR_CvLct-yfsKe4sDj_WcOBmvW_VtuA
# Token Client
@client = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIyMTQxODd9.XfMS9TBBa9U-lI5bG9RHNO48i_H-LFKQmJqCcCQ5Jws
# Refresh Token
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTI1NzAyMTh9.siyuYHRmxzB1Eh30MJ_oLqFbVQqURQMx9lkH_eNm5IM

# DEFAULT TOKEN (Ubah variabel ini untuk mengganti role aktif)
@token = {{owner}}

###
# GROUP: ENUMERATION
###

### GET GENRE
GET {{host}}/v1/_enum?app_name=baseapp&module=GENRE
Authorization: Bearer {{token}}

### GET CONTENT STATUS
GET {{host}}/v1/_enum/from/common/ContentStatus
Authorization: Bearer {{token}}

### GET LANGUAGE
GET {{host}}/v1/_enum/from/common/LanguageCode
Authorization: Bearer {{token}}

### GET RESOLUTION
GET {{host}}/v1/_enum/from/common/ContentResolution
Authorization: Bearer {{token}}

### GET LICENSE
GET {{host}}/v1/_enum/from/common/LicenseFrom
Authorization: Bearer {{token}}

### GET TERRITORY
GET {{host}}/v1/_enum/from/common/Territory
Authorization: Bearer {{token}}

### GET HLS Filter
GET {{host}}/v1/_enum/from/common/DocumentTypeFilterHLS
Authorization: Bearer {{token}}

###
# GROUP: CONTENT
###

### Create
# status: DRAFT, PUBLISHED, UNPUBLISHED, SCHEDULED, ARCHIVED
# is_full_paid=true → full_price_coins wajib
# license_from=terisi → licence_date wajib
# main_sponsor=null → optional, jika terisi {org_id, brand_name, campaign_name}
POST {{host}}/v1/content/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title":{
        "en":"Love Story at School",
        "id":"Kisah Kasih Di Sekolah"
    }, 
    "synopsis":{
        "en":"Love Story",
        "id":"Kisah Kasih"
    }, 
    "genre":["9a4c0f5a9c2a4b15bfaee6db589d6068"],
    "release_date": "2025-03-20T00:00:00Z", 
    "cast":["Alex", "Siska"], 
    "tags":["CEO love triangle", "Money and Power"], 
    "mature_content": false, 
    "license_from": null, 
    "licence_date_start": null,
    "licence_date_end": null,
    "origin": "Indonesia", 
    "territory": ["Indonesia"], 
    "is_full_paid": true,
    "full_price_coins": 840,
    "main_sponsor": null,
    "status": "DRAFT"
}


### Update
# main_sponsor=null → optional, jika terisi {org_id, brand_name, campaign_name}
PUT {{host}}/v1/content/update/8a66f138350e401d919d9125511fc7ab
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "title":{
        "en":"Love Story at School",
        "id":"Kisah Kasih Di Sekolah"
    }, 
    "synopsis":{
        "en":"Love Story",
        "id":"Kisah Kasih"
    },
    "genre":["9a4c0f5a9c2a4b15bfaee6db589d6068","6ee3557896624c599d091bd174d2abab"],
    "release_date": "2025-03-20T00:00:00Z", 
    "cast":["Alex", "Siska"], 
    "tags":["CEO love triangle", "Money and Power"], 
    "mature_content": false,  
    "license_from": null, 
    "licence_date_start": null,
    "licence_date_end": null,
    "origin":"Indonesia", 
    "territory":["Indonesia"], 
    "is_full_paid":true,
    "full_price_coins":840,
    "main_sponsor": {
        "org_id":"8a8f5e1e-3f4b-4f4b- ninth-8d6e5c6f7a2b",
        "brand_id":"8a8f5e1e-3f4b-4f4b- ninth-8d6e5c6f7a2b"
    }
}


### Set Published
PUT {{host}}/v1/content/update_status/8a66f138350e401d919d9125511fc7ab
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "status":"PUBLISHED" 
}


### List
GET {{host}}/v1/content
Authorization: Bearer {{token}}


### Find By ID
GET {{host}}/v1/content/find/fc3d27cf64274413ab74b3f72122707b
Authorization: Bearer {{token}}

### Find By Brand
# /{brand_id}?title_contains=string
GET {{host}}/v1/content/by-brand/fc3d27cf64274413ab74b3f72122707b
Authorization: Bearer {{token}}


###
# GROUP: ATTACHMENT
###

### Upload Poster
POST {{upload_host}}/v1/_dms/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="5c413e87e562f5654dd5c3dceb51b75182c9495b.png"
< ./path/to/5c413e87e562f5654dd5c3dceb51b75182c9495b.png
--boundary
Content-Disposition: form-data; name="doctype"

64c1c7ba4a5246648bf224bfd19fe118
--boundary
Content-Disposition: form-data; name="metadata"

{"Content ID":"fc3d27cf64274413ab74b3f72122707b", "Title":"Kisah Kasih Di Sekolah", "Language":"ID"}
--boundary
Content-Disposition: form-data; name="refkey_id"

fc3d27cf64274413ab74b3f72122707b
--boundary
Content-Disposition: form-data; name="refkey_table"

content
--boundary
Content-Disposition: form-data; name="refkey_name"

poster
--boundary--


### Upload FYP
POST {{upload_host}}/v1/_dms/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="fyp.mp4"
< ./path/to/fyp.mp4
--boundary
Content-Disposition: form-data; name="doctype"

31c557f0f4574f7aae55c1b6860a2e19
--boundary
Content-Disposition: form-data; name="metadata"

{"Content ID":"728f1a79-b8e2-42ca-860d-6535aaa45a57", "Title":"Kisah Kasih Di Sekolah", "Language":"ID", "Resolution":"HD"}
--boundary
Content-Disposition: form-data; name="refkey_id"

728f1a79-b8e2-42ca-860d-6535aaa45a57
--boundary
Content-Disposition: form-data; name="refkey_table"

content
--boundary
Content-Disposition: form-data; name="refkey_name"

fyp
--boundary--


### Upload FYP 2
POST {{upload_host}}/v1/_dms/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="highlight.mp4"
< ./path/to/highlight.mp4
--boundary
Content-Disposition: form-data; name="doctype"

3551a74699394f22b21ecf8277befa39
--boundary
Content-Disposition: form-data; name="metadata"

{"Content ID":"728f1a79-b8e2-42ca-860d-6535aaa45a57", "Title":"Kisah Kasih Di Sekolah", "Language":"ID", "Resolution":"HD"}
--boundary
Content-Disposition: form-data; name="refkey_id"

728f1a79-b8e2-42ca-860d-6535aaa45a57
--boundary
Content-Disposition: form-data; name="refkey_table"

content
--boundary
Content-Disposition: form-data; name="refkey_name"

highlight
--boundary--


###
# GROUP: BROWSE ATTACHMENT
###
GET {{host}}/v1/_dms/browse/key/content/fc3d27cf64274413ab74b3f72122707b
Authorization: Bearer {{token}}

###
# HLS: Video Check
###
GET {{host}}/v1/stream/hls/4845cbb7e2384723abeb4ff09bcbf2a/check

###
# HLS: Video Get URL
###
GET {{host}}/v1/stream/hls/4845cbb7e2384723abeb4ff09bcbf2a?folder_name=4845cbb7e2384723abeb4ff09bcbf2a1

###
# HLS: Video Get URL New
###
GET {{host}}/v1/stream/hls/e2a64aef3e844bf394aa5ab913ad51d7/fyp_1
