@prod = https://arena.gai.co.id/service
@dev = http://localhost:1899
@host = {{prod}}
@upload_host = {{prod}}

# --- TOKENS ---
# Token Owner (Arena)
@owner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBnYWkuY28uaWQiLCJpZCI6ImY1NjM1ZjQyLWNlNWQtNGEwYy05ZGY2LWU4Njk2ZDdiOTgxOSIsInJvbGVzIjpbIjFkYjg3OWU2LTI1NTMtNDE5Ny1hZjc5LWQ1MDA2YTJjMGE4YiJdLCJhdXRob3JpdHkiOjEsIm9yZ19pZCI6ImQzNzdlYjg5LTIyZjMtNDU2ZC04NmMzLTE1MDczZDUxNDhjYSIsImZlYXR1cmVzIjp7Il91c2VyIjo3LCJfcm9sZSI6MTUsIl9lbnVtIjoxNSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfbWVudSI6NSwiX29yZ2FuaXphdGlvbiI6NywiX2Rhc2hib2FyZCI6MSwiX215b3JnIjo1LCJfbXlwcm9maWxlIjo1LCJfZG1zaW5kZXhsaXN0IjoxNSwiX2Rtc2RvY3R5cGUiOjE1LCJfZG1zYnJvd3NlIjoxNTksInN1YnNjcmlwdGlvbl9wbGFuIjo3fSwiYml0d3MiOnsiYWRkIjoyLCJhcHByb3ZhbCI6NjQsImRlbGV0ZSI6OCwiZWRpdCI6NCwiZXhwb3J0IjoxNiwiaW1wb3J0IjozMiwic2V0dGluZyI6MTI4LCJ2aWV3IjoxfSwiZXhwIjoxNzUyMjk0MjM3fQ.Lq9NlGyHjlZ4f1Jk5iEtrxGSB1PKb7VDaS600suGrk4
# Token Partner
@partner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBwZWphdGVuLXBoLmNvbSIsImlkIjoiMzY3Mjg1YzUtYWJiYS00NjgzLWJkYzItNTU0ZTQzZWQ1YzM2Iiwicm9sZXMiOlsiY2E3MDQwNGQtYjY1NC00ZGFiLThkMDQtNDFiN2E1YjA0MTQ4IiwiOWQyOTgxNjgtMmMzMi00YjVkLWE5MTUtMmFkNzVhZjdhYWMwIl0sImF1dGhvcml0eSI6Miwib3JnX2lkIjoiNjdiODFmYzAtNTk1NC00YTkzLWJlOGUtNTllZmU2ZWFhNGNlIiwiZmVhdHVyZXMiOnsiX3VzZXIiOjcsIl9yb2xlIjoxNSwiX2VudW0iOjEsIl9hdWRpdHRyYWlsIjoxLCJfZmVhdHVyZSI6NSwiX29yZ2FuaXphdGlvbiI6NywiX2Rhc2hib2FyZCI6MSwiX215b3JnIjo1LCJfbXlwcm9maWxlIjo1LCJfZG1zaW5kZXhsaXN0IjoxLCJfZG1zZG9jdHlwZSI6MSwiX2Rtc2Jyb3dzZSI6MTU5LCJjb250ZW50IjoxODN9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIxMzU5MjF9.12jBjfswWoeFtR_CvLct-yfsKe4sDj_WcOBmvW_VtuA
# Token Client
@client = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIyMTQxODd9.XfMS9TBBa9U-lI5bG9RHNO48i_H-LFKQmJqCcCQ5Jws
# Refresh Token
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTI1NzAyMTh9.siyuYHRmxzB1Eh30MJ_oLqFbVQqURQMx9lkH_eNm5IM

# DEFAULT TOKEN (Ubah variabel ini untuk mengganti role aktif)
@token = {{owner}}

###
# GROUP: CONTENT (ENUM)
###
### GET GENRE
GET {{host}}/v1/_enum?app_name=baseapp&module=GENRE
Authorization: Bearer {{token}}

### GET CONTENT STATUS
GET {{host}}/v1/_enum/from_model/ContentStatus
Authorization: Bearer {{token}}

###
# GROUP: CONTENT (HEADER)
###
### Create
POST {{host}}/v1/content/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"Kisah Kasih Di Sekolah", 
    "description":"Kisah Kasih", 
    "cast":"Alex, Siska", 
    "genre":["23c41302-37f8-4fb5-8845-9dc721f76ffa"],
    "release_date": "2025-03-20T00:00:00Z", 
    "license_date": "2025-03-20T00:00:00Z", 
    "episodes":60, 
    "duration":120,
    "origin":"Indonesia", 
    "is_full_paid":true,
    "full_price_coins":840,
    "main_sponsor":{
        "org_id":"8a8f5e1e-3f4b-4f4b- ninth-8d6e5c6f7a2b",
        "brand_name":"BrandX",
        "campaign_name":"Campaign Spring"
    },
    "status":"DRAFT"
}

### Upload Poster (Content)
POST {{upload_host}}/v1/_dms/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="thumb.png"
< ./path/to/thumb.png
--boundary
Content-Disposition: form-data; name="doctype"

8e79c84ee66542db9aa5a1252c47530d
--boundary
Content-Disposition: form-data; name="metadata"

{"Content ID":"728f1a79-b8e2-42ca-860d-6535aaa45a57"}
--boundary
Content-Disposition: form-data; name="refkey_id"

728f1a79-b8e2-42ca-860d-6535aaa45a57
--boundary
Content-Disposition: form-data; name="refkey_table"

content
--boundary
Content-Disposition: form-data; name="refkey_name"

poster
--boundary--

### Update
PUT {{host}}/v1/content/update/728f1a79-b8e2-42ca-860d-6535aaa45a57
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "name":"Kisah Kasih Di Sekolah", 
    "description":"Updated", 
    "cast":"Alex", 
    "genre":[], 
    "release_date": "2025-03-20T00:00:00Z", 
    "license_date": "2025-03-20T00:00:00Z", 
    "episodes":60, 
    "duration":120,
    "origin":"Indonesia", 
    "is_full_paid":true,
    "full_price_coins":840,
    "main_sponsor":{
        "org_id":"8a8f5e1e-3f4b-4f4b- ninth-8d6e5c6f7a2b",
        "brand_name":"BrandX",
        "campaign_name":"Campaign Spring"
    }
}


### Set Published
PUT {{host}}/v1/content/update_status/728f1a79-b8e2-42ca-860d-6535aaa45a57
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "status":"PUBLISHED" 
}

### List
GET {{host}}/v1/content?status=PUBLISHED
Authorization: Bearer {{token}}

### Explore
GET {{host}}/v1/content/explore?status=PUBLISHED

### Find
GET {{host}}/v1/content/find/728f1a79-b8e2-42ca-860d-6535aaa45a57
Authorization: Bearer {{token}}

###
# GROUP: CONTENT (DETAIL/EPISODE)
###
### Create Episode
POST {{host}}/v1/content-detail/create
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "content_id":"728f1a79-b8e2-42ca-860d-6535aaa45a57", 
    "title":"Pandangan Pertama", 
    "description":"Episode 1 Description", 
    "episode":1, 
    "duration":1, 
    "release_date": "2025-03-20T00:00:00Z",
    "is_free":false,
    "episode_price":21,
    "episode_sponsor":{
        "org_id":"8a8f5e1e-3f4b-4f4b- ninth-8d6e5c6f7a2b",
        "brand_name":"BrandY",
        "campaign_name":"Campaign Summer"
    },
    "status":"DRAFT" 
}

### Upload Video
POST {{upload_host}}/v1/_dms/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="video.mp4"
< ./path/to/video.mp4
--boundary
Content-Disposition: form-data; name="doctype"

8e79c84ee66542db9aa5a1252c47530d
--boundary
Content-Disposition: form-data; name="metadata"

{"Content ID":"728f1a79-b8e2-42ca-860d-6535aaa45a57","Video ID":"40825a75-0a39-4dec-8dc6-ad1bcedc98cc","Eps":1}
--boundary
Content-Disposition: form-data; name="refkey_id"

40825a75-0a39-4dec-8dc6-ad1bcedc98cc
--boundary
Content-Disposition: form-data; name="refkey_table"

content_video
--boundary
Content-Disposition: form-data; name="refkey_name"

video
--boundary--

### Update Detail
PUT {{host}}/v1/content-detail/update/40825a75-0a39-4dec-8dc6-ad1bcedc98cc
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "content_id":"728f1a79-b8e2-42ca-860d-6535aaa45a57", 
    "title":"Pandangan Pertama", 
    "description":"Episode 1 Description", 
    "episode":1, 
    "duration":1, 
    "release_date": "2025-03-20T00:00:00Z", 
    "revise_date": "2025-03-20T00:00:00Z", 
    "is_free":false,
    "episode_price":21,
    "episode_sponsor":{
        "org_id":"8a8f5e1e-3f4b-4f4b- ninth-8d6e5c6f7a2b",
        "brand_name":"BrandY",
        "campaign_name":"Campaign Summer"
    },
    "status":"DRAFT" 
}

### Set Status Episode
PUT {{host}}/v1/content-detail/update_status/40825a75-0a39-4dec-8dc6-ad1bcedc98cc
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "status":"PUBLISHED" 
}

### List Episode
GET {{host}}/v1/content-detail?content_id=728f1a79-b8e2-42ca-860d-6535aaa45a57
Authorization: Bearer {{token}}

### Find Episode
GET {{host}}/v1/content-detail/find/40825a75-0a39-4dec-8dc6-ad1bcedc98cc
Authorization: Bearer {{token}}