@prod = https://arena.gai.co.id/service
@dev = http://localhost:17178
@host = {{dev}}
@upload_host = {{prod}}

# --- TOKENS ---
# Token Owner (Arena)
@owner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBhcmVuYS5jby5pZCIsImlkIjoiODY5Y2RjZDcwZjFmNDM4ZGFhMDEyOTFmZjZlZDRjZGIiLCJyb2xlcyI6WyIwNTRhODBlYTA3Mzk0YTg0YTc0MWRjYWQ4OWM1ZjBiZiJdLCJhdXRob3JpdHkiOjEsIm9yZ19pZCI6ImJhYzUxODk3NWMzZDQ1MGU4NDYxOGYxNjk0ZmVkNzcyIiwiZmVhdHVyZXMiOnsiX3VzZXIiOjcsIl9yb2xlIjo3LCJfZW51bSI6MTUsIl9hdWRpdHRyYWlsIjoxLCJfZmVhdHVyZSI6NSwiX21lbnUiOjUsIl9vcmdhbml6YXRpb24iOjcsIl9kYXNoYm9hcmQiOjEsIl9teW9yZyI6NSwiX215cHJvZmlsZSI6NSwiX2Rtc2luZGV4bGlzdCI6NywiX2Rtc2RvY3R5cGUiOjcsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTkxLCJ3YWxsZXQiOjcsInRvcHVwIjo3LCJhZHMiOjEsInFyX3Byb2R1Y3QiOjEsImJ1bmRsaW5nIjoxLCJnaXZlYXdheSI6MX0sImJpdHdzIjp7IlZJRVciOjEsIkFERCI6MiwiRURJVCI6NCwiREVMRVRFIjo4LCJFWFBPUlQiOjE2LCJJTVBPUlQiOjMyLCJBUFBST1ZBTCI6NjQsIlNFVFRJTkciOjEyOH0sInNlc3Npb25faWQiOiIwZDgzMGVkOTcxMTA0MmMzODAyMmNiYTA1MzIzM2M5YSIsImV4cCI6MTc2NTk1OTk0MSwianRpIjoiMjk0MGI0MDEyMzQ0NDc1OThhMzZjNjNkZjIwNzM0ZmYifQ.FI4poPZYkX5I0MWcqVaad6kULg9yEad5GPgDzcTmfH8
# Token Partner
@partner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBwZWphdGVuLXBoLmNvbSIsImlkIjoiMzY3Mjg1YzUtYWJiYS00NjgzLWJkYzItNTU0ZTQzZWQ1YzM2Iiwicm9sZXMiOlsiY2E3MDQwNGQtYjY1NC00ZGFiLThkMDQtNDFiN2E1YjA0MTQ4IiwiOWQyOTgxNjgtMmMzMi00YjVkLWE5MTUtMmFkNzVhZjdhYWMwIl0sImF1dGhvcml0eSI6Miwib3JnX2lkIjoiNjdiODFmYzAtNTk1NC00YTkzLWJlOGUtNTllZmU2ZWFhNGNlIiwiZmVhdHVyZXMiOnsiX3VzZXIiOjcsIl9yb2xlIjoxNSwiX2VudW0iOjEsIl9hdWRpdHRyYWlsIjoxLCJfZmVhdHVyZSI6NSwiX29yZ2FuaXphdGlvbiI6NywiX2Rhc2hib2FyZCI6MSwiX215b3JnIjo1LCJfbXlwcm9maWxlIjo1LCJfZG1zaW5kZXhsaXN0IjoxLCJfZG1zZG9jdHlwZSI6MSwiX2Rtc2Jyb3dzZSI6MTU5LCJjb250ZW50IjoxODN9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIxMzU5MjF9.12jBjfswWoeFtR_CvLct-yfsKe4sDj_WcOBmvW_VtuA
# Token Client
@client = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIyMTQxODd9.XfMS9TBBa9U-lI5bG9RHNO48i_H-LFKQmJqCcCQ5Jws
# Refresh Token
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTI1NzAyMTh9.siyuYHRmxzB1Eh30MJ_oLqFbVQqURQMx9lkH_eNm5IM

# DEFAULT TOKEN (Ubah variabel ini untuk mengganti role aktif)
@token = {{owner}}

### GET DATA TYPE ENUM
GET {{host}}/v1/_enum/from/common/DMSDataType
Authorization: Bearer {{token}}

###
# GROUP: DMS (INDEX)
###

### CREATE
POST {{host}}/v1/_dms/index/create
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "name":"Resolution", 
    "description":"SD, HD, 4K", 
    "type":"String", 
    "status":"ACTIVE" 
}

### UPDATE
PUT {{host}}/v1/_dms/index/update/5892d554706a48539ba7954e0278bfd7
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "description":"Updated", 
    "type":"String", 
    "status":"ACTIVE" 
}

### DELETE
PUT {{host}}/v1/_dms/index/delete/5892d554706a48539ba7954e0278bfd7
Authorization: Bearer {{token}}
Content-Type: application/json

### GET by Options
GET {{host}}/v1/_dms/index?type=String&status=ACTIVE&name_contains=episode
Authorization: Bearer {{token}}

### GET by ID
GET {{host}}/v1/_dms/index/find/5892d554706a48539ba7954e0278bfd7
Authorization: Bearer {{token}}


###
# GROUP: DMS (DOCTYPE)
###

### CREATE
POST {{host}}/v1/_dms/doctype/create
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "name":"Subtitle", 
    "metadata":["Content ID","Title","Language","Episode ID","Eps"], 
    "folder":"Media >> {Content ID} >> Episode >> {Eps} >> Subtitle", 
    "mapping":{"Content ID":"_id","Title":"title","Language":"language", "Episode ID":"_id", "Eps":"episode"}, 
    "status":"ACTIVE" 
}

### UPDATE
PUT {{host}}/v1/_dms/doctype/update/4a626e3ebb8242a7b448a6203af4aefb
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "metadata":["Content ID","Eps","Language","Episode ID"], 
    "folder":"Media >> {Content ID} >> Episode >> {Eps} >> Dubber", 
    "mapping":{"Content ID":"content_id","Eps":"episode", "Language":"language", "Episode ID":"_id"}, 
    "status":"ACTIVE" 
}

### DELETE
DELETE {{host}}/v1/_dms/doctype/delete/95a871c8cc0c4225a064676031b4249f
Authorization: Bearer {{token}}
Content-Type: application/json

### GET by Options
GET {{host}}/v1/_dms/doctype?name=Poster&status=ACTIVE&name_contains=poster
Authorization: Bearer {{token}}

### GET by ID
GET {{host}}/v1/_dms/doctype/find/d67d38fe623b40ccb0ddb4671982c0d3
Authorization: Bearer {{token}}

###
# GROUP: DMS (BROWSE)
###

### DELETE BY FILE
DELETE {{host}}/v1/_dms/browse/delete_file/2ce39be1-2bda-4a1f-b2b1-6a3156fac471
Authorization: Bearer {{token}}

### DELETE BY FOLDER
DELETE {{host}}/v1/_dms/browse/delete_folder/48a72cca-871c-46f4-ac74-8649e2a011d5
Authorization: Bearer {{token}}

### MOVE TO TRASH BY FILE
PUT {{host}}/v1/_dms/browse/sent_file/to_trash/28e8545f-dd1e-4a1c-a8ec-be0270797512
Authorization: Bearer {{token}}

### RESTORE FROM TRASH BY FILE
PUT {{host}}/v1/_dms/browse/sent_file/restore/28e8545f-dd1e-4a1c-a8ec-be0270797512
Authorization: Bearer {{token}}

### BROWSE FILES IN FOLDER
GET {{host}}/v1/_dms/browse/folder/48a72cca-871c-46f4-ac74-8649e2a011d5
Authorization: Bearer {{token}}

### GET STORAGE INFO
GET {{host}}/v1/_dms/browse/storage
Authorization: Bearer {{token}}

###
# GROUP: DMS (UPLOAD)
###
POST {{upload_host}}/v1/_dms/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="image.png"
< ./path/to/image.png
--boundary
Content-Disposition: form-data; name="doctype"

b58cf688-2244-464c-be95-3b2ba4a18bbf
--boundary
Content-Disposition: form-data; name="metadata"

{"Company":"GAI"}
--boundary
Content-Disposition: form-data; name="refkey_id"

5a480134-2b7f-479f-9883-d4b902113186
--boundary
Content-Disposition: form-data; name="refkey_table"

history
--boundary
Content-Disposition: form-data; name="refkey_name"

bukti_bayar
--boundary--