@prod = https://arena.gai.co.id/service
@dev = http://localhost:17178
@host = {{prod}}
@upload_host = {{dev}}

@session_id = d44e20de5f364f2da698f346c8bbc90d

###
# GROUP: Register (Traditional)
###
POST {{host}}/v1/register
Content-Type: application/json
X-Client-Type: mobile

{ 
    "email": "aldian.gnusa@gmail.com", 
    "phone_number": "085778789851" ,
    "password": "SecurePassword123" 
}

###
# GROUP: Resend OTP
###
POST {{host}}/v1/register/resend_otp
Content-Type: application/json
X-Client-Type: mobile

{ 
    "session": "5ae492ab7ef8440e960431aa2907939a"
}

###
# GROUP: Verify
###
POST {{host}}/v1/register/verify
Content-Type: application/json
X-Client-Type: mobile

{ 
    "session": "bcbd77ef4dae4c818b1d71ed9d34ba2b",
    "otp": "572968"
}

###
# GROUP: Register (Google OAuth)
###
PUT {{host}}/v1/oauth/register-google-account
Content-Type: application/json

{ 
    "access_token":"ya29.a0AZYkNZhPzqHTFZ28GCnWI4VnoSKQPHGh1OAXLgHiGQ9EPHjTcqL4OP2F0TzMoySZIM30tWhzIP-8d_zQnI0Ci6omHzcCnZ6jTCpIPc2UNq0r2enHLWXxaIO0yyH3XXJyc0tUYkPe3_TbIaRCV0YAKbynBIlKEz_GKweSd-x-aCgYKAbASARUSFQHGX2MiLNDiLXUYJxvSOifr7RRc9g0175" 
}