@prod = https://arena.gai.co.id/service
@dev = http://localhost:1899
@host = {{dev}}
@upload_host = {{dev}}

# --- TOKENS ---
# Token Owner (Arena)
@owner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBnYWkuY28uaWQiLCJpZCI6ImY1NjM1ZjQyLWNlNWQtNGEwYy05ZGY2LWU4Njk2ZDdiOTgxOSIsInJvbGVzIjpbIjFkYjg3OWU2LTI1NTMtNDE5Ny1hZjc5LWQ1MDA2YTJjMGE4YiJdLCJhdXRob3JpdHkiOjEsIm9yZ19pZCI6ImQzNzdlYjg5LTIyZjMtNDU2ZC04NmMzLTE1MDczZDUxNDhjYSIsImZlYXR1cmVzIjp7Il91c2VyIjo3LCJfcm9sZSI6MTUsIl9lbnVtIjoxNSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfbWVudSI6NSwiX29yZ2FuaXphdGlvbiI6NywiX2Rhc2hib2FyZCI6MSwiX215b3JnIjo1LCJfbXlwcm9maWxlIjo1LCJfZG1zaW5kZXhsaXN0IjoxNSwiX2Rtc2RvY3R5cGUiOjE1LCJfZG1zYnJvd3NlIjoxNTksInN1YnNjcmlwdGlvbl9wbGFuIjo3fSwiYml0d3MiOnsiYWRkIjoyLCJhcHByb3ZhbCI6NjQsImRlbGV0ZSI6OCwiZWRpdCI6NCwiZXhwb3J0IjoxNiwiaW1wb3J0IjozMiwic2V0dGluZyI6MTI4LCJ2aWV3IjoxfSwiZXhwIjoxNzUyMjk0MjM3fQ.Lq9NlGyHjlZ4f1Jk5iEtrxGSB1PKb7VDaS600suGrk4
# Token Partner
@partner = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBwZWphdGVuLXBoLmNvbSIsImlkIjoiMzY3Mjg1YzUtYWJiYS00NjgzLWJkYzItNTU0ZTQzZWQ1YzM2Iiwicm9sZXMiOlsiY2E3MDQwNGQtYjY1NC00ZGFiLThkMDQtNDFiN2E1YjA0MTQ4IiwiOWQyOTgxNjgtMmMzMi00YjVkLWE5MTUtMmFkNzVhZjdhYWMwIl0sImF1dGhvcml0eSI6Miwib3JnX2lkIjoiNjdiODFmYzAtNTk1NC00YTkzLWJlOGUtNTllZmU2ZWFhNGNlIiwiZmVhdHVyZXMiOnsiX3VzZXIiOjcsIl9yb2xlIjoxNSwiX2VudW0iOjEsIl9hdWRpdHRyYWlsIjoxLCJfZmVhdHVyZSI6NSwiX29yZ2FuaXphdGlvbiI6NywiX2Rhc2hib2FyZCI6MSwiX215b3JnIjo1LCJfbXlwcm9maWxlIjo1LCJfZG1zaW5kZXhsaXN0IjoxLCJfZG1zZG9jdHlwZSI6MSwiX2Rtc2Jyb3dzZSI6MTU5LCJjb250ZW50IjoxODN9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIxMzU5MjF9.12jBjfswWoeFtR_CvLct-yfsKe4sDj_WcOBmvW_VtuA
# Token Client
@client = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTIyMTQxODd9.XfMS9TBBa9U-lI5bG9RHNO48i_H-LFKQmJqCcCQ5Jws
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4X3BlamF0ZW5AZ21haWwuY29tIiwiaWQiOiIxZDYzODQ4Yy0xMzYyLTQwMzQtOTBiNS0xMmVmODYzZGMzZTMiLCJyb2xlcyI6WyJlNTBiMTdlYS0wM2E0LTQ0OWUtYThhZS1kOGY3M2FjMDM3NzEiXSwiYXV0aG9yaXR5Ijo0LCJvcmdfaWQiOiIyYjIyYjE1MS00NjQ0LTQ4NTMtYmM4ZS0zMTYyMjdkMTQxMzAiLCJmZWF0dXJlcyI6eyJfdXNlciI6NywiX3JvbGUiOjE1LCJfZW51bSI6MSwiX2F1ZGl0dHJhaWwiOjEsIl9mZWF0dXJlIjo1LCJfZGFzaGJvYXJkIjoxLCJfbXlvcmciOjUsIl9teXByb2ZpbGUiOjUsIl9kbXNpbmRleGxpc3QiOjE1LCJfZG1zZG9jdHlwZSI6MTUsIl9kbXNicm93c2UiOjE1OSwiY29udGVudCI6MTd9LCJiaXR3cyI6eyJhZGQiOjIsImFwcHJvdmFsIjo2NCwiZGVsZXRlIjo4LCJlZGl0Ijo0LCJleHBvcnQiOjE2LCJpbXBvcnQiOjMyLCJzZXR0aW5nIjoxMjgsInZpZXciOjF9LCJleHAiOjE3NTI1NzAyMTh9.siyuYHRmxzB1Eh30MJ_oLqFbVQqURQMx9lkH_eNm5IM

# DEFAULT TOKEN (Ubah variabel ini untuk mengganti role aktif)
@token = {{owner}}

###
# GROUP: PROFILE
###

### Profile User
GET {{host}}/v1/profile/user
Authorization: Bearer {{token}}

### Profile Organization
GET {{host}}/v1/profile/organization
Authorization: Bearer {{token}}

### Change Password
PUT {{host}}/v1/_user/change_password
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "old_password":"playup123", 
    "new_password":"SecurePassword123", 
    "verify_password":"SecurePassword123" 
}

###
# GROUP: ROLE
###

### Create Role
POST {{host}}/v1/_role/create
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "color":"red", 
    "name":"User", 
    "status":"ACTIVE" 
}

### Update Role
PUT {{host}}/v1/_role/update/c1b1d2fb-e21b-45a4-81e2-dba355868749
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "color":"red", 
    "name":"Finance", 
    "status":"ACTIVE" 
}

### List Roles
GET {{host}}/v1/_role
Authorization: Bearer {{token}}

### Get Role By ID
GET {{host}}/v1/_role/find/c1b1d2fb-e21b-45a4-81e2-dba355868749
Authorization: Bearer {{token}}

###
# GROUP: USER
###

### Create User
POST {{host}}/v1/_user/create
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "username":"finance@countify.com", 
    "email":"finance@countify.com", 
    "password":"finance123", 
    "roles":["c1b1d2fb-e21b-45a4-81e2-dba355868749"], 
    "status":"ACTIVE" 
}

### Update User
PUT {{host}}/v1/_user/update/5849d05d-43c5-4f8f-96cb-cdd6968fe01b
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "username":"finance@countify.com", 
    "email":"finance@countify.com", 
    "roles":["c1b1d2fb-e21b-45a4-81e2-dba355868749"], 
    "status":"ACTIVE" 
}

### Delete User
DELETE {{host}}/v1/_user/delete/5849d05d-43c5-4f8f-96cb-cdd6968fe01b
Authorization: Bearer {{token}}
Content-Type: application/json

### Get All Users
GET {{host}}/v1/_user?page=1&sort_field=status&per_page=10
Authorization: Bearer {{token}}